limit_req_zone $binary_remote_addr zone=zaochang_preview_per_ip:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=zaochang_preview_static_per_ip:10m rate=64r/s;
limit_conn_zone $binary_remote_addr zone=zaochang_preview_connections:10m;
